Fix ABI break on getTraceMetadata (#395)
Prevent `NoSuchMethodError` on `Tracer.getTraceMetadata` caused by ABI break when using `tracing-okhttp` <=4.1.0 and `tracing` 4.2.0.