Tracing aware executors add a single stack frame, down from four
Firstly, we should not optimize around stack depth in most cases
because it can result in large methods that the JVM cannot efficiently
inline and additional GC pressure depending on the implementation.

However, we use tracing a lot, a tracing wrapped executor shows up
in ~50% of stack traces in a large internal service, and exceptions
propagate through multiple executors in many cases.
This would not make sense to change if the tracing stack frames
provided information, but wrapping from runnable to callable
isn't helpful, nor are lambda frames to turn a Callable into
a ThrowingCallable.

This change is completely internal to tracing and does not expose
any new public APIs.

Before: frames 2, 3, 4, and 5 are from tracing
```
com.palantir.logsafe.exceptions.SafeRuntimeException: Stack Trace
        at com.palantir.tracing.TracerTest.lambda$testStackDepth$9(TracerTest.java:486)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.palantir.tracing.DeferredTracer.withTrace(DeferredTracer.java:104)
        at com.palantir.tracing.Tracers$TracingAwareCallable.call(Tracers.java:356)
        at com.palantir.tracing.WrappingExecutorService.lambda$wrapTask$0(WrappingExecutorService.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

After: line 2 handles tracing, the rest would be present without tracing
```
com.palantir.logsafe.exceptions.SafeRuntimeException: Stack Trace
        at com.palantir.tracing.TracerTest.lambda$testStackDepth$9(TracerTest.java:486)
        at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```